---
version: '2'

tasks:
  default:

  init:
    cmds:
      - terraform init
  plan:
    deps:
      [init]
    cmds:
      - terraform plan
  clean:
    cmds:
      - rm -fr .terraform/
  apply:
    deps:
      [init]
    cmds:
      - terraform apply
  destroy:
    cmds:
      - terraform destroy
